version: '3.6'
services:
  authentication_api:
    build:
      context: api
    container_name: authentication_api
    restart: unless-stopped
    # depends_on:
    #   authentication_dev_db:
    #     condition: service_healthy
    depends_on:
      - authentication_dev_db

    volumes:
      - "./api:/var/www"
    ports:
      - "8080:80"
    networks:
      - authentication-network
    healthcheck:
      # test: ["CMD", "wget", "--no-verbose", "--tries=1",  "http://localhost:80"]
      # test: wget --no-verbose --tries=1 --spider http://localhost:80 || exit 1
      test: curl --fail http://localhost:80 || exit 1
      retries: 4
      timeout: 2s
      start_period: 5s

  test-deno:
    build:
      context: test-end2end/api/deno
    container_name: test-deno
    # command: deno test --allow-all
    volumes:
      - "./test-end2end/api/deno:/test"
    depends_on:
      authentication_api:
        condition: service_healthy

  test-http:
    build:
      context: test-end2end/api/http
    container_name: test-end2end
    networks:
      - authentication-network
    volumes:
      - "./test-end2end/api:/test"
    depends_on:
      authentication_api:
        condition: service_healthy
    command: httpyac send **/*.http --all --env production --output-failed exchange --output none

  # front:
  #   tty: true
  #   restart: unless-stopped
  #   container_name: authentication_front
  #   build:
  #     context: frontend
  #     target: builder
  #   command: sh -c 'npm start'
  #   ports:
  #     - '4200:4200'
  #   volumes:
  #     - "./frontend:/app"
  #     - /app/node_modules
  #   networks:
  #     - authentication-network


  authentication_dev_db:
    image: mysql:5.7
    container_name: authentication_dev_db
    restart: unless-stopped
    # healthcheck:
    #   test: mysqladmin ping -pkhj-aDSdlkh23423_123asd || exit 1
    #   retries: 4
    #   timeout: 2s
    #   start_period: 1s
    ports:
     - '3306:3306'
    volumes:
      - 'dbdata:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: khj-aDSdlkh23423_123asd
      MYSQL_DATABASE: authentication_dev_db
    networks:
      - authentication-network


  authentication_adminer:
    image: adminer
    container_name: authentication_adminer
    restart: unless-stopped
    ports:
      - 8081:8080
    environment:
      ADMINER_PLUGINS: tables-filter tinymce
      PMA_HOST: authentication_dev_db
    depends_on:
      - authentication_dev_db
    networks:
      - authentication-network

  maildev:
    image: maildev/maildev
    ports:
      - "1080:80"
      # - "1025:1025"
    networks:
      - authentication-network

volumes:
  dbdata:
networks:
  authentication-network:
    name: authentication-network
