# FROM node:17-alpine
FROM node:17
WORKDIR /test
# RUN apk add curl
RUN apt-get install curl -y

RUN groupadd -r test && useradd -g test test
ENV DENO_INSTALL=/deno/
RUN mkdir -p $DENO_INSTALL \
    && curl -fsSL https://deno.land/x/install/install.sh | sh \
    && chown -R test $DENO_INSTALL

ENV PATH=${DENO_INSTALL}/bin:${PATH} \
    DENO_DIR=${DENO_INSTALL}/.cache/deno

RUN deno --version
RUN npm i -g httpyac
USER test
# CMD ["httpyac", "**/*.http", "--all","-e", "production", "-o", "short" ]
CMD ["deno","test","--allow-all"] ]