@host={{API_HOST}}


###
GET /user
###

POST /auth/signup
Content-Type:application/json

{
  "email": "juan@geekshubs.com",
  "password": "Pa$$word952!"
}

{{
  test.status(200);
}}

###


POST /auth/signup
Content-Type:application/json

{
  "email": "juangeekshubs.com",
  "password": "Pa$$word952!"
}

{{
  test.status(422);
}}

###


POST /auth/signup
Content-Type:application/json

{
  "email": "juan@geekshubs.com",
  "password": "1234"
}

{{
  test.status(422);
}}

###


POST /auth/signup
Content-Type:application/json

{
  "email": "email@en.uso",
  "password": "Pa$$word952!"
}

{{
  // test.status(409);
  const { equal } = require('assert');
  test('status code 409', () => {
    equal(response.statusCode,409)
  });

  test('body has error', async () => {
      const body = await response.json();
      // expect(body).to.have.property('errors');
      equal(body.error.length,3);
  });
}}

###